### PR TITLE
type Leistung

### PR DESCRIPTION
**Pull request by westnordost**
### Issue
- the `leistung` field for the `ELS` segment should contain a completely different information depending on the type of Leistung, i.e. depending on the value of `verguetungsart`. This makes it to cite yourself "insanely complex"
- there is no documentation in PAID to help what kind of data is expected depending on the value of `verguetungsart`. As a user of this library, one would need to read through the GKV docs again to find out what one is expected to specify.
- the current Leistung type is in this regard misleading because it suggests that e.g. the Wegegeld or the Pflegehilfsmittel used is to be (or can be) specified in one Leistung together with e.g. a Leistung nach Zeitvergütung. This is not the case. To bill Zeitvergütung + Wegegeld + Pflegehilfsmittel, three Leistungen need to be billed, not one.

### Solution
Just type it. A Leistung can be a "Wegegeld Leistung", a "Zeitvergütung Leistung", a "Pflegehilfsmittel Leistung" etc.
Depending on the type of Leistung, different fields are mandatory and the fields are named and typed according to what should be filled in.

### CODE REVIEW

**Comment by westnordost** [comment]
In the implemented solution, `leistungsBeginn` and `leistungsEnde` is optional in all types of `Leistung`, even though `leistungsBeginn` is only mandatory for `verguetungsart` 04 and `leistungsEnde` is only mandatory for `verguetungsart` 01, 02, 03 or 04. I did this because you have some logic in `index.ts` that assumes that any Leistung potentially has these fields defined (for grouping and sorting Leistungen by time/date). I wasn't sure if you'd be okay with changing this logic. You might argue that for convenience/consistency reasons, you'd want the user in coop-care to always specify the start and end time of any Leistung in the UI even though it is not necessary for billing.

**Comment by westnordost** [comment]
Review note: Look at [types.ts](https://github.com/coop-care/paid/pull/48/files#diff-3626a77725ed59cd21752ef6ca1ff660aad90ba2b3773a19d956124f26a97df4) first.

**Review by michaelkamphausen — COMMENTED** [review]
I like that you make the previously implicit and intransparent knowledge about the possible values for the property leistung explicitly visible with the differentiation of the Leistung datatype. A true improvement.

I'm only a little unhappy about the splitting of WegegebuehrenSchluessel, because I rate cost/benefit differently here. I would rather keep the data types more simple and think gefahreneKilometer would also be sufficient as an optional property and self-explanatory in connection with the four values of WegegebuehrenSchluessel. In case of doubt, documentation and validation can provide clarity.

Would that modification be acceptable to you?

**Comment by westnordost** [comment]
It has been some time since I looked at it. But I think that's fair enough - if the type is remove, there should simply be a documentation comment that explains that hte optional field is actually mandatory if XYZ.

Do you expect me to change this or will you do it?

**Comment by michaelkamphausen** [comment]
I will take care of it.

**Pull request merged**
