### PR TITLE
add clarifications from answer from GKV-Spitzenverband

### PR DESCRIPTION
**Pull request by westnordost**
The clarifications for our questions regarding SGB-V arrived.

No code changes were necessary. Only documentation. 

This is just FYI, there is no review required. You can merge it unseen, if you like.

### CODE REVIEW

**Comment by westnordost** [comment]
Maybe one question here: There is still one unanswered question in https://mzh.nc.coopcare.de/index.php/apps/files/?dir=/PAID/Recherchen&openfile=57310 (the last one)

I could ask this as a follow-up, but I think you told me some months ago already that certain people/orgs are simply allocated to certain _Sammelgruppen_ and there is no switching from Einsatz to Einsatz, right?

**Comment by westnordost** [comment]
@michaelkamphausen

**Comment by michaelkamphausen** [comment]
I think this is still a valid question. I have a presumption about an answer, but I think it would be helpful to ask this question to get more certainty.

My presumption is that it depends on the application process whether the Sammelgruppenschlüssel C or D applies.
Haushaltshilfe (D) is applied for directly to the health insurance company by the people themselves who do not usually need help or care, but who are temporarily unable to run their household and are therefore dependent on Haushaltshilfe, e.g. due to injury, hospitalization, pregnancy, etc..
Differentiating from this, any care requested via a Verordnung by a physician (Muster 12) would be Häusliche Krankenpflege (C). I also learned that "hauswirtschaftliche Versorgung" on that Verordnung form is not equal to "Haushaltshilfe", although they are the same kind of activities.
However, both C and D can be performed by the same care provider, but following this assumption probably not for the same client.

**Comment by westnordost** [comment]
ok, I sent the question

**Comment by michaelkamphausen** [comment]
Thanks!

**Pull request merged**
